### PR TITLE
[FEATURE] CRUD functionality added

### PR DESCRIPTION
**Pull request by sethpthomas91**

### CODE REVIEW

**Comment by martingaston** [comment]
morning! 

I'd recommend you always split your bootstrapping PR from any actual logic, because you've got a +2500 line PR and your reviewers are going to have to filter through generated code and your bespoke logic, and the former is almost certainly going to be reviewed in a separate way. To be blunt, the first feeling of a reviewer when seeing a +2500 line/57 file PR that's a mix of boilerplate and custom code is probably to think 'oh heavens, I'll look at this _much, much later_' and kick it down the road. 

other small (but generally quite important, imo) nitpicks: 

- _No description provided_: unless your reviewer is _extremely_ close to what you've been working on, this gigantic PR is going to hit like a freight train. Does `CRUD functionality added` capture the context accurately? What's in scope? What's out of scope? Can you link to a ticket on your kanban board where this is discussed? I would default to assuming your reviewers are time poor, so any steps you can make to make their job of reviewing easier is going to boost your chances of getting a good review. I've been on multiple projects where this PR would probably languish as unreviewed for days on end and then when somebody finally got around to reviewing it, you'd have to deal with a dozen merge conflicts because the codebase would have drifted significantly from when you wrote it. No fun for anyone!
- The prerequisites in your `README.md` don't mention anything about a database, but your config files seem to be setup for postgres.
- You raised in your retro that you wanted to write more shell scripts, but there's absolutely no CI/CD present in this PR? Feels like a missed opportunity. Is that part of your walking skeleton? As an aside, this is an area where it's usually beneficial to be more diligent - https://trello.com/c/YL9DECsw/68-8-mobile-ttt-release-1-crud-api-and-basic-front mentions 'walking skeleton' and, if I was your client stakeholder, I would read that and 100% expect to see CI if we've moved that ticket to 'Done'. Managing expectations around scope is, in my opinion, one of the single most important parts of a healthy and productive client relationship.

**Comment by sethpthomas91** [comment]
@martingaston- For the bootstrapping vs functionality, I was asked to have some functionality before I get my first pull request in. It moved us right past the walking skeleton version and started getting us focused on features right away. I would agree that the walking skeleton naming was wrong for this release and that is why the feature is called CRUD functionality. I'll make sure to add more description for the next pull.

Agreed on not mentioning the database as an oversight. Can you leave in-line comments on those specific issues so I can tic them off on the PR next time?

**Comment by scottyplunkett** [comment]
@sethpthomas91 you should add DB stuff in README to this PR. Also edit the description. You should get in the habit of making changes in the course of a PR and those 2 are small enough that they shouldn't do anything crazy when you go to rebase any other branches you have going.

Here's a PR template that we use at Groupon that's helpful for PR Descriptions... each time we edit it, deleting lines we don't need, and adjusting ones we do to fill in specific details... you could use something similar, changing out the JIRA links for links to your trello board, and of course ripping out the stuff that doesn't make sense:

```
Review [FED-FILL_ME_IN](https://jira.groupondev.com/browse/FED-FILL_ME_IN) before reviewing code changes.

Paired with @user

### Added
* What was added?
### Changed
* What was changed?
### Removed
* What was removed?
### Fixed
* What was fixed?

---

### Pre-merge Checklist
- [ ] Update Jira ticket links section to point to this PR
- [ ] All tests pass
- [ ] Verify in staging
- [ ] Consider performance impact
- [ ] Consider impact to other teams/services
- [ ] Consider post-deploy monitoring plan
- [ ] Update documentation? (README, [Owner's Manual](https://pages.github.groupondev.com/finance-engineering/fed_services/fts/), [Service Portal](https://services.groupondev.com/services/file-transfer/))
- [ ] Update [monitoring](https://groupon.wavefront.com/dashboard/file-transfer)?

Review requested from @user(s), @sox-inscope/finance-engineering-ro

```

**Comment by scottyplunkett** [comment]
I also think @martingaston was suggesting that the PR is just too big to review and that's why I asked you to have the bootstrapped stuff in `main` before this PR. That was my intent at least. Can you try splitting out the code and files generated from the command line _a la_ `mix phx.new ...`, and push that stuff to `main`... then rebase this branch onto that and push back up so we can review the changes since bootstrapping?

**Pull request closed without merging**
